### ISSUE TITLE
Creative Commons licenses not good for code

### ISSUE THREAD

**Issue by aariops** [JerryPadfield/RemoteRadio#1]
Hey, Jerry!

This is a great tool :heart_eyes: 

However, [CC licenses are not encouraged for code](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software). 

You can pick a more suitable license using the [Choose a License](https://choosealicense.com) website. 

Cheers

**Comment by JerryPadfield** [comment]
Thanks Rute,

This was an error. Supposed to be MIT License (hence the inclusion in the README). Now fixed :)

**Comment by aariops** [comment]
Awesome!
